# Generated by Django 5.2.15 on 2026-07-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='debtor_creditor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
