# Generated by Django 5.2.15 on 2026-07-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_debtor_creditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
